// <auto-generated />
using System;
using DogusProject.Models.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogusProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogusProject.Models.Repositories.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = new Guid("1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a"),
                            CategoryId = 1,
                            CommentId = 0,
                            Content = "Son yıllarda yapay zeka (YZ) alanında yaşanan gelişmeler, teknoloji dünyasında devrim niteliğinde değişimlere yol açtı. Derin öğrenme, makine öğrenimi ve doğal dil işleme konularındaki ilerlemeler sayesinde, yapay zeka artık sadece teorik bir alan olmaktan çıkıp günlük hayatımızın ayrılmaz bir parçası haline geldi. Sağlık sektöründen otomotive, eğitimden finansal analizlere kadar birçok alanda yapay zeka çözümleri aktif olarak kullanılmakta. Örneğin, hastalıkların erken teşhisi için geliştirilen yapay zeka tabanlı sistemler, doktorların işini kolaylaştırırken, hata oranını da ciddi şekilde azaltıyor. Öte yandan, otonom araçlar, sürücüsüz ulaşımın kapılarını aralarken, doğal dil işleme ile geliştirilen chatbot ve dijital asistanlar, müşteri hizmetlerinde devrim yaratıyor. GPT-4 ve benzeri büyük dil modelleri, metin oluşturma, özetleme, çeviri gibi alanlarda insan performansına yakın sonuçlar veriyor. Bu gelişmeler, önümüzdeki yıllarda daha da hız kazanacak gibi görünüyor. Ancak etik ve güvenlik konuları da her zamankinden daha fazla önem taşıyor.",
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg\n",
                            Title = "Yapay Zeka Gelişmeleri"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = new Guid("1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a"),
                            CategoryId = 2,
                            CommentId = 0,
                            Content = "Kapadokya, Türkiye'nin en büyüleyici doğal güzelliklerinden biri olarak her yıl binlerce turisti kendine çekiyor. Geçtiğimiz hafta sonu gerçekleştirdiğim Kapadokya gezisi, adeta başka bir dünyaya yolculuk gibiydi. Peribacalarıyla ünlü bu bölge, tarih boyunca birçok medeniyete ev sahipliği yapmış. Göreme Açık Hava Müzesi, bölgedeki en dikkat çeken duraklardan biri. Eski dönemden kalma kaya kiliseler ve freskler, insanı derinden etkiliyor. Sabah erken saatlerde yapılan sıcak hava balonu turu ise geziye bambaşka bir boyut kazandırıyor. Gökyüzünden Kapadokya'yı izlemek, kelimelerle tarif edilemeyecek kadar etkileyiciydi. Ayrıca yerel mutfak da oldukça zengin; testi kebabı, çömlek fasulyesi gibi yöresel tatları denemek kesinlikle unutulmaz bir deneyim. Bölgede konaklama için ise taş oteller oldukça otantik ve konforlu. Bu gezi, hem doğa hem de kültür meraklıları için tam anlamıyla bir cennet niteliğinde. Kapadokya, her adımda yeni bir keşif sunuyor.",
                            CreatedAt = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.pexels.com/photos/3889704/pexels-photo-3889704.jpeg\n",
                            Title = "Kapadokya Gezisi"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = new Guid("2b2b2b2b-2b2b-2b2b-2b2b-2b2b2b2b2b2b"),
                            CategoryId = 3,
                            CommentId = 0,
                            Content = "İtalyan mutfağı, dünya genelinde en çok sevilen ve en çok bilinen mutfaklardan biridir. Özellikle makarna ve pizza denilince ilk akla gelen ülke olan İtalya, aslında çok daha geniş bir lezzet yelpazesine sahiptir. Bölgesel farklılıklar mutfağa büyük çeşitlilik katıyor. Örneğin, kuzey bölgelerinde tereyağı ve kremalı soslar yaygınken, güneyde daha çok zeytinyağı ve domates bazlı soslar kullanılıyor. Risotto, lasagna, gnocchi gibi lezzetler İtalyan mutfağının temel taşları arasında yer alıyor. Ayrıca, zeytinyağı, sarımsak, taze otlar ve peynirler mutfağın vazgeçilmezleri arasında. Tatlılar da oldukça iddialı; tiramisu, panna cotta ve cannoli gibi lezzetler damakta iz bırakıyor. İtalyanlar yemek hazırlamayı bir sanat olarak görüyor ve bu da yemeğin lezzetine yansıyor. Her yemeğin ardında bir hikâye ve gelenek var. İtalyan mutfağını bu kadar özel yapan da, hem basit hem de derin bir lezzet anlayışına sahip olmasıdır. Yemek yemeyi değil, yaşamayı öğretiyor adeta.",
                            CreatedAt = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "İtalyan Mutfağı"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = new Guid("2b2b2b2b-2b2b-2b2b-2b2b-2b2b2b2b2b2b"),
                            CategoryId = 4,
                            CommentId = 0,
                            Content = "Futbol, sadece fiziksel bir spor değil, aynı zamanda strateji ve zeka oyunudur. Modern futbolda taktik anlayışı her geçen gün evrilmekte. Artık takımlar sadece bireysel yeteneklere değil, sistemli oyun planlarına da büyük önem veriyor. 4-3-3, 3-5-2, 4-2-3-1 gibi dizilişler oyunun temposunu ve seyrini ciddi şekilde etkileyebiliyor. Örneğin, Pep Guardiola'nın pas oyunu (tiki-taka) ile Jurgen Klopp'un gegenpressing sistemi, farklı ama etkili futbol anlayışlarının örnekleri olarak öne çıkıyor. Takım savunması, alan daraltma, hızlı geçiş oyunları gibi detaylar, maçın kaderini belirleyebiliyor. Aynı zamanda bireysel rollerin doğru belirlenmesi de kritik. Bir orta saha oyuncusunun hem savunma hem hücumda aktif rol alabilmesi, takım dengesini doğrudan etkiliyor. Teknolojinin ilerlemesiyle birlikte analiz sistemleri ve veriye dayalı taktik geliştirme araçları da yaygınlaştı. Artık her antrenman, her maç, hatta her oyuncu hareketi detaylı analiz ediliyor. Taktik bilgi kadar uygulama becerisi de başarıda belirleyici oluyor.",
                            CreatedAt = new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg\n",
                            Title = "Futbol Taktikleri"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = new Guid("3c3c3c3c-3c3c-3c3c-3c3c-3c3c3c3c3c3c"),
                            CategoryId = 5,
                            CommentId = 0,
                            Content = "Bu yıl katıldığım tiyatro festivali, sanatın ve sahne performanslarının büyüsünü bir kez daha hissettirdi. Festival boyunca farklı ülkelerden gelen tiyatro topluluklarının sahnelediği oyunlar, seyircilere adeta kültürel bir yolculuk yaşattı. Klasik eserlerden modern oyunlara, her biri farklı mesajlar ve duygular barındıran performanslar izledik. Özellikle minimalist sahne tasarımları ve yaratıcı kostümler, oyuncuların performansını daha da öne çıkardı. Seyircilerle etkileşimli sahneler, tiyatronun canlı ve dinamik yapısını ortaya koydu. Ayrıca festival kapsamında düzenlenen atölye çalışmaları ve söyleşiler, tiyatroya ilgi duyanlar için büyük bir öğrenme fırsatı sundu. Sahne arkasındaki emek, ışık tasarımı, müzik kullanımı gibi detaylar da oldukça etkileyiciydi. Tiyatro, insan ruhuna dokunan en güçlü sanat dallarından biri. Bu festival, yalnızca oyun izlemek değil, aynı zamanda sanatın birleştirici ve düşündürücü gücüne tanık olmak açısından da çok anlamlıydı.",
                            CreatedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tiyatro Festivali"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = new Guid("3c3c3c3c-3c3c-3c3c-3c3c-3c3c3c3c3c3c"),
                            CategoryId = 1,
                            CommentId = 0,
                            Content = "Dijital dönüşüm, sadece bir teknoloji yenilenmesi değil, aynı zamanda kurumların iş yapış biçimlerini kökten değiştiren bir süreçtir. Özellikle pandemi sonrası hız kazanan bu dönüşüm, artık tüm sektörlerde kaçınılmaz hale gelmiş durumda. Bulut bilişim, yapay zeka, büyük veri ve nesnelerin interneti gibi teknolojiler, iş dünyasında yeni fırsatlar yaratıyor. Şirketler daha çevik, verimli ve müşteri odaklı olmak adına dijital altyapılarını yeniden yapılandırıyor. Örneğin, dijitalleşen bir müşteri hizmetleri birimi, hem maliyetleri düşürürken hem de müşteri memnuniyetini artırabiliyor. Aynı zamanda çalışanlar için de daha esnek ve verimli bir iş ortamı sağlanıyor. Ancak bu dönüşüm sürecinde siber güvenlik, veri gizliliği ve çalışan eğitimi gibi konular da büyük önem taşıyor. Dijital dönüşüm sadece teknolojik değil, kültürel bir değişimi de beraberinde getiriyor. Kurumların bu değişime ayak uydurabilmesi, rekabet avantajı kazanmaları için kritik bir faktör. Bu nedenle dijital dönüşüm bir seçenek değil, bir zorunluluktur.",
                            CreatedAt = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dijital Dönüşüm"
                        });
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Teknoloji"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Seyahat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yemek"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Spor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kültür-Sanat"
                        });
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            CommentText = "Harika bir yazı olmuş!",
                            CreatedAt = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("2b2b2b2b-2b2b-2b2b-2b2b-2b2b2b2b2b2b")
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            CommentText = "Çok faydalı bilgiler.",
                            CreatedAt = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("3c3c3c3c-3c3c-3c3c-3c3c-3c3c3c3c3c3c")
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            CommentText = "Ben de gitmeyi düşünüyorum.",
                            CreatedAt = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("3c3c3c3c-3c3c-3c3c-3c3c-3c3c3c3c3c3c")
                        });
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATICSTAMP1",
                            Email = "ahmet@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET@EXAMPLE.COM",
                            NormalizedUserName = "AHMET.YILMAZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEG3ZzqZ5Ez0XdbM7HzBDtLXMDF54QF9d54YbZlMYU1JArXs1xDBSMV5n25fu+RI1fQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATICSTAMP1",
                            TwoFactorEnabled = false,
                            UserName = "ahmet.yilmaz"
                        },
                        new
                        {
                            Id = new Guid("2b2b2b2b-2b2b-2b2b-2b2b-2b2b2b2b2b2b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATICSTAMP2",
                            Email = "mehmet@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHMET@EXAMPLE.COM",
                            NormalizedUserName = "MEHMET.KAYA",
                            PasswordHash = "AQAAAAIAAYagAAAAEP1JYtdUqMeQOB9b3oPO3ReAOtbvU1GNlU55L8w5gAuI8lF0ZXwGlCmG9R2SvdvVaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATICSTAMP2",
                            TwoFactorEnabled = false,
                            UserName = "mehmet.kaya"
                        },
                        new
                        {
                            Id = new Guid("3c3c3c3c-3c3c-3c3c-3c3c-3c3c3c3c3c3c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATICSTAMP3",
                            Email = "ayse@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AYSE@EXAMPLE.COM",
                            NormalizedUserName = "AYSE.DEMIR",
                            PasswordHash = "AQAAAAIAAYagAAAAEMU1Uw2hAeGlObBGImMychTuM6Q4syuUw19GMymGkTLc4eXsLT+bN9iF4HTuATlMBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATICSTAMP3",
                            TwoFactorEnabled = false,
                            UserName = "ayse.demir"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Blog", b =>
                {
                    b.HasOne("DogusProject.Models.Repositories.Entities.AppUser", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogusProject.Models.Repositories.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Comment", b =>
                {
                    b.HasOne("DogusProject.Models.Repositories.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogusProject.Models.Repositories.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("DogusProject.Models.Repositories.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DogusProject.Models.Repositories.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DogusProject.Models.Repositories.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("DogusProject.Models.Repositories.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogusProject.Models.Repositories.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DogusProject.Models.Repositories.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Blog", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Category", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("DogusProject.Models.Repositories.Entities.AppUser", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
